# Conclusion

Overall I was able to discover a several interesting trends with my data. To highlight a few from the results page: BMI within each age group was stable across cycles but varied across age groups, women report more aerobic training than strength training, and over the last ten years physical activity levels have increased across the country, with western states being the most active.

The most challenging portion of the project was loading in, understanding, and cleaning my data. I thought since it came from the CDC it would be a bit cleaner and more manageable to work with. However, having to source, download, and combine a different dataset for each topic I wanted to look at was challenging to manage which is why I went with three cycles, then a second dataset that was more comprehensive. I also thought some of the datasets would be a bit more detailed, ie more than just a yes/no question for fertility issues. So I felt that overall the project had more breadth than depth of looking into different aspects of each topic. I think if I were able to get a dataset from a source like a fertility clinic there would have been a lot more there to dive into, though the participants would be more representative of a subset with fertility issues. Changes to the survey in the 21-23 cycle were also disappointed as I had mentioned in the Data chapter.

Though once my data was finally in a stable place and I really grasped the features I wanted to focus on, I was very surprised how quickly I had ideas for ten different graphs for my dataset. I thought it would be a bit challenging but as I really started working with the data I got into more of a flow with my project and felt a more natural progression in the visuals I was making.

I really enjoyed completing this as it was the first end-to-end project I've done in awhile. It helped reinforce my data cleaning, how combining individual and aggregated data can round out insights, and how different visuals can really make a difference in the way you look at and interpret data.
