# Introduction


For my final project I am interested in exploring trends in women's health factors. For the past three years I have worked part time as a group fitness instructor, with the majority of my clients being women. My perception being in the field is that women are becoming increasingly involved with fitness, with the broader boutique studio business also growing rapidly to meet demand. I also find that with social media, we see trends of more women discussing their health online. I've also noticed these trends beginning to be picked up by media and consultant agencies, with McKinsey stating "Wellness is more important to consumers than ever. In the United States alone, we estimate that it represents more than $500 billion in annual spend, growing at 4 to 5 percent each year."


I am curious to dive into the data to see the real story the numbers are telling. Have reported physical activity levels changed? Are women in certain areas of the country more concerned with their health than others? Another factor that is of interest to me is how fitness levels relate to other features seen in the dataset. If time permits I'd like to dive into some of the data available on miscarriages, hormone treatments, etc and visualize some of the trends there as well.


sources:

https://www.mckinsey.com/industries/consumer-packaged-goods/our-insights/future-of-wellness-trends
https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx
https://data.cdc.gov/Behavioral-Risk-Factors/Behavioral-Risk-Factor-Surveillance-System-BRFSS-P/dttw-5yxu/about_data

